# -*- coding: utf-8 -*-
"""
Created on Wed Sep 26 13:46:05 2012

@author: "Benjamin Reh"
"""
from sys import argv
from math import pi, sin, cos


h=2.0
r1=2.0
r2=1.0
n=10

#class triangle

print "# generated by cone.py"
print "#  written by Benjamin Reh, 2012"
print "# h="+str(h),"r2="+str(r1),"r2="+str(r2),"n="+str(n)
print "s 1"

vertexcounter=0

d_alpha=2*pi/(float(n))
for i in range(0,n):
    print "v", 0.0, 0.0 ,-h/2
    print "v", sin(float(i)*d_alpha)*r2, cos(float(i)*d_alpha)*r2 ,-h/2
    print "v", sin(float(i+1)*d_alpha)*r2, cos(float(i+1)*d_alpha)*r2 ,-h/2
    print "vn",0.,0.,-1.
    print "vn",0.,0.,-1.
    print "vn",0.,0.,-1.
    vertexcounter+=3
    print "f ",str(vertexcounter-2)+"//"+str(vertexcounter-2),str(vertexcounter-1)+"//"+str(vertexcounter-1),str(vertexcounter)+"//"+str(vertexcounter)

    print "v", 0.0, 0.0 ,h/2
    print "v", sin(float(i+1)*d_alpha)*r1, cos(float(i+1)*d_alpha)*r1 ,h/2
    print "v", sin(float(i)*d_alpha)*r1, cos(float(i)*d_alpha)*r1 ,h/2

    print "vn",0.,0.,1.
    print "vn",0.,0.,1.
    print "vn",0.,0.,1.
    vertexcounter+=3
    print "f ",str(vertexcounter-2)+"//"+str(vertexcounter-2),str(vertexcounter-1)+"//"+str(vertexcounter-1),str(vertexcounter)+"//"+str(vertexcounter)



    
    print "v", sin(float(i+1)*d_alpha)*r1, cos(float(i+1)*d_alpha)*r1 ,h/2
    print "v", sin(float(i)*d_alpha)*r2, cos(float(i)*d_alpha)*r2 ,-h/2
    print "v", sin(float(i)*d_alpha)*r1, cos(float(i)*d_alpha)*r1 ,h/2

    print "vn", sin(float(i+1)*d_alpha), cos(float(i+1)*d_alpha) ,0
    print "vn", sin(float(i)*d_alpha), cos(float(i)*d_alpha), 0
    print "vn", sin(float(i)*d_alpha), cos(float(i)*d_alpha) ,0
    
    vertexcounter+=3
    print "f ",str(vertexcounter-2)+"//"+str(vertexcounter-2),str(vertexcounter-1)+"//"+str(vertexcounter-1),str(vertexcounter)+"//"+str(vertexcounter)
    
    print "v", sin(float(i+1)*d_alpha)*r1, cos(float(i+1)*d_alpha)*r1 ,h/2
    print "v", sin(float(i+1)*d_alpha)*r2, cos(float(i+1)*d_alpha)*r2 ,-h/2
    print "v", sin(float(i)*d_alpha)*r2, cos(float(i)*d_alpha)*r2 ,-h/2

    print "vn", sin(float(i+1)*d_alpha), cos(float(i+1)*d_alpha), 0    
    print "vn", sin(float(i+1)*d_alpha), cos(float(i+1)*d_alpha) ,0
    print "vn", sin(float(i)*d_alpha), cos(float(i)*d_alpha) ,0
    
    vertexcounter+=3
    print "f ",str(vertexcounter-2)+"//"+str(vertexcounter-2),str(vertexcounter-1)+"//"+str(vertexcounter-1),str(vertexcounter)+"//"+str(vertexcounter)

