#ifndef _MESHUP_CONFIG_H
#define _MESHUP_CONFIG_H

#cmakedefine MESHUP_VERSION_STRING "@MESHUP_VERSION_STRING@"
#cmakedefine MESHUP_INSTALL_PREFIX "@MESHUP_INSTALL_PREFIX@"

 /* _MESHUP_CONFIG_H */
#endif
